### PR TITLE
You are now a data analyst.

### PR DESCRIPTION
**Pull request by IonicaBizau**
I noticed you're not an accountant anymore, but a data analyst! :tada:
If I could, I would update the [about me page](http://alysonla.com/about-me/) as well. :smile:

### CODE REVIEW

**Comment by alysonla** [comment]
@IonicaBizau sorry didn't get the ping the first time! You are :sparkles:

**Comment by Rican7** [comment]
:clap:

**Comment by IonicaBizau** [comment]
@alysonla Probably because you're not :eyes: this repository. You were notified only when I mentioned you. Thanks for merging and keep up the good work!  :clap: :fireworks: :star2:

**Pull request merged**
